### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by geertschuring** [wildfly-extras/wildfly-camel-examples#150]
After cloning the repo and trying to build it I get an exception trying to download org.picketbox:picketbox:jar:5.0.3.Final-redhat-00005

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Wildfly Camel :: Example 12.1.0-SNAPSHOT:
[INFO]
[INFO] Wildfly Camel :: Example ........................... SUCCESS [  0.305 s]
[INFO] Wildfly Camel :: Example :: Camel ActiveMQ ......... SUCCESS [ 14.863 s]
[INFO] Wildfly Camel :: Example :: Camel CDI .............. SUCCESS [  0.173 s]
[INFO] Wildfly Camel :: Example :: Camel CXF JAX-RS ....... SUCCESS [  2.355 s]
[INFO] Wildfly Camel :: Example :: Camel CXF JAX-RS Secure  SUCCESS [  0.232 s]
[INFO] Wildfly Camel :: Example :: Camel CXF JAX-WS ....... SUCCESS [  0.202 s]
[INFO] Wildfly Camel :: Example :: Camel CXF JAX-WS CDI Secure FAILURE [  4.086 s]
[INFO] Wildfly Camel :: Example :: Camel CXF JAX-WS CDI XML SKIPPED
[INFO] Wildfly Camel :: Example :: Camel CXF JAX-WS Secure  SKIPPED
[INFO] Wildfly Camel :: Example :: Camel JMS .............. SKIPPED
[INFO] Wildfly Camel :: Example :: Camel JMS MDB .......... SKIPPED
[INFO] Wildfly Camel :: Example :: Camel JMS Spring ....... SKIPPED
[INFO] Wildfly Camel :: Example :: Camel JMS Tx ........... SKIPPED
[INFO] Wildfly Camel :: Example :: Camel JMS Tx Spring .... SKIPPED
[INFO] Wildfly Camel :: Example :: Camel JPA .............. SKIPPED
[INFO] Wildfly Camel :: Example :: Camel JPA Spring ....... SKIPPED
[INFO] Wildfly Camel :: Example :: Camel Mail ............. SKIPPED
[INFO] Wildfly Camel :: Example :: Camel Mail Spring ...... SKIPPED
[INFO] Wildfly Camel :: Example :: Camel REST Swagger ..... SKIPPED
[INFO] Wildfly Camel :: Example :: Testsuite .............. SKIPPED
[INFO] Wildfly Camel :: Example :: Distro ................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  24.681 s
[INFO] Finished at: 2020-07-28T17:51:04+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project example-camel-cxf-jaxws-cdi-secure: Could not resolve dependencies for project org.wildfly.camel.example:example-camel-cxf-jaxws-cdi-secure:war:12.1.0-SNAPSHOT: Could not find artifact org.picketbox:picketbox:jar:5.0.3.Final-redhat-00005 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

**Comment by jamesnetherton** [comment]
Thanks for reporting this. The master branch should be fixed now.

**Comment by geertschuring** [comment]
Hi James,

Thanks for the update. Downloading the dependencies now works. However, I run into two other problems, the first is that there seems to be some platform based EOL problems. 

This is my output of a gitt pull and a mvn clean install:

[Build output.txt](https://github.com/wildfly-extras/wildfly-camel-examples/files/5014917/Build.output.txt)

After executing the suggested command the EOL problem was fixed, but then several tests failed:

[Build output 2.txt](https://github.com/wildfly-extras/wildfly-camel-examples/files/5014933/Build.output.2.txt)

Looks like there are tests that are environmentally dependant and fail when the host does not have the expected IP adres.

Regards,
Geert.

**Comment by jamesnetherton** [comment]
The IP address problem is a bit weird. The value comes from `InetAddress.getLocalHost().getHostAddress()`. Seems strange that the test is expecting a different value to what is reported on the server side...

Maybe it would be better to use (or maybe fallback on) the value of system property `jboss.bind.address`?

**Comment by geertschuring** [comment]
To give you some context that might help, here's my systems ipconfig:

C:\Users\geert\git\wildfly-camel-examples>ipconfig

Windows IP Configuration


Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . : Hitronhub.home
   IPv4 Address. . . . . . . . . . . : 192.168.0.18
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 192.168.0.1

Ethernet adapter vEthernet (Default Switch):

   Connection-specific DNS Suffix  . :
   IPv4 Address. . . . . . . . . . . : 192.168.38.177
   Subnet Mask . . . . . . . . . . . : 255.255.255.240
   Default Gateway . . . . . . . . . :
