### ISSUE TITLE
http://java.sun.com/xml/ns/persistence/persistence_2_1.xsd doesn't exist

### ISSUE THREAD

**Issue by apupier** [wildfly-extras/wildfly-camel-examples#58]
it is referenced in the persistence.xml file but ti doesn't exist, is it http://www.oracle.com/webfolder/technetwork/jsc/xml/ns/persistence/persistence_2_1.xsd with http://xmlns.jcp.org/xml/ns/persistence which should be used instead?

**Comment by jamesnetherton** [comment]
Probably xmlns.jcp.org. Here's what the WildFly quickstarts use:

https://github.com/wildfly/quickstart/blob/c3a8ec0ac68e79e938c3e5da20a88c4bab8e89e0/jts/application-component-1/src/main/resources/META-INF/persistence.xml

**Comment by jamesnetherton** [comment]
ok to test
