### ISSUE TITLE
Set Doctype for xml file without schemas

### ISSUE THREAD

**Issue by apupier** [wildfly-extras/wildfly-camel-examples#61]
it avoids to have warnings in Eclipse

**Comment by apupier** [comment]
I fixed several warnings with this PR https://github.com/wildfly-extras/wildfly-camel-examples/pull/63
but there are still several files reporting errors:
"No grammar constraints (DTD or XML Schema) referenced in the document."

![image](https://user-images.githubusercontent.com/1105127/31555644-17b1d71a-b042-11e7-9446-2f14590540c0.png)

they contain a schemalocation without a real location, is it a fake schemalocation? Do we really need it?

**Comment by jamesnetherton** [comment]
Probably not needed. Think I took the XML structure from another Fuse / Camel quickstart.

If the tests pass with it removed, I'm fine with removing it.

**Comment by jamesnetherton** [comment]
Thanks for pointing this out. I fixed up the erroneous schema locations in the other files.

I also corrected the` !DOCTYPE` declaration. Think it needs to be `<!DOCTYPE root_element_name>` instead of `<!DOCTYPE xml>`.
