### ISSUE TITLE
Transacted component must have a child defined

### ISSUE THREAD

**Issue by apupier** [wildfly-extras/wildfly-camel-examples#66]
![image](https://user-images.githubusercontent.com/1105127/31605723-3f406310-b267-11e7-8484-76bff4e1e592.png)

the camel-jms-tx-spring examples have none.

based on https://github.com/apache/camel/blob/master/camel-core/src/main/java/org/apache/camel/model/TransactedDefinition.java#L159 Transactedcomponents must have a child defined as it is calling with mandatory parameter to "true".
https://github.com/apache/camel/blob/ac17984f89c0e27d504b621e1f8d851bc9077076/camel-core/src/main/java/org/apache/camel/model/ProcessorDefinition.java#L195

**Comment by jamesnetherton** [comment]
If this is invalid, surely it should fail at runtime? But it works fine. See debug session screenshot below:

![transacted-debug](https://user-images.githubusercontent.com/4721408/31619687-2d84d824-b28d-11e7-9746-c55ac4207e87.png)

**Comment by apupier** [comment]
in this case, there is a bug in camel-maven-plugin for validation and in Fuse Tooling

**Comment by jamesnetherton** [comment]
Is there anything needed on our side here or can I close this one?

**Comment by apupier** [comment]
> Is there anything needed on our side here or can I close this one?

I would say that we will need to sort out what is the issue exactly and why Fuse Tooling and camel-maven-plugin is reporting an error.
