### ISSUE TITLE
Expand examples based on customer feedback

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel-examples#7]
CrossRef: https://github.com/wildfly-extras/wildfly-camel/issues/1386

**Comment by tdiesler** [comment]
Waiting on @sundarmr whether he want to transform these such that they are actually using the wildfly-camel integration

**Comment by sundarmr** [comment]
Hi Thomas
Yes I want to transform the code examples to use wildly-camel
Regards
Sundar M R

**Comment by tdiesler** [comment]
Ok, look forward to seeing the first cut

**Comment by jamesnetherton** [comment]
Any news on this? I think pulling in some of the Spring examples would be useful as we often get questions around developing WildFly-Camel apps with Spring, and we have no examples other than test cases.

**Comment by tdiesler** [comment]
This has moved back to: wildfly-extras/wildfly-camel#1386
