### ISSUE TITLE
Revisit the way we setup the appserver

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel-examples#81]
Currently a number of manual steps are needed before a quickstart can run from Eclipse 

See [ENTESB-7903](https://issues.jboss.org/browse/ENTESB-7903). This can perhaps be improved by some other setup procedure that also works from the IDE (and not only from the mvn cmd line)

**Comment by jamesnetherton** [comment]
#122 took care of this.
