### ISSUE TITLE
Camel ActiveMQ Example

### ISSUE THREAD

**Issue by sankintoo** [wildfly-extras/wildfly-camel-examples#92]
Could you please also describe how to enable activeMQ in wildfly-camel subsystem. The example does not work.  I followed this link https://wildfly-extras.github.io/wildfly-camel/#_camel_activemq

Artifact example-camel-activemq:war: java.lang.Exception: {"WFLYCTL0412: Required services that are not installed:" => ["jboss.naming.context.java.ActiveMQConnectionFactory"],"WFLYCTL0180: Services with missing/unavailable dependencies" => ["jboss.naming.context.java.module.example-camel-activemq.example-camel-activemq.env.amq-connection-factory is missing [jboss.naming.context.java.ActiveMQConnectionFactory]"]}

thank you.
Sanjeev.

**Comment by jamesnetherton** [comment]
Seems like the ConnectionFactory cannot be discovered.

Is the ActiveMQ resource adapter deployed and configured on your server?

The example can do this for you with:
```
mvn install -Pdeploy-rar
```
You'll need to restart the app server afterwards for the configuration to take effect.

**Comment by sankintoo** [comment]
This is how it is configured in standalone-full.xml
The activemq-rar.rar is present under deployment folder.
After starting Wildfly, I do not see any registration on activeMQ.

<subsystem xmlns="urn:jboss:domain:resource-adapters:4.0" >
		 <resource-adapters>
         <resource-adapter id="activemq-rar.rar">
             <archive>
                 activemq-rar.rar
             </archive>
             <transaction-support>XATransaction</transaction-support>
             <config-property name="UseInboundSession">
                 false
             </config-property>
             <config-property name="Password">
                 defaultPassword
             </config-property>
             <config-property name="UserName">
                 defaultUser
             </config-property>
             <config-property name="ServerUrl">
                 tcp://localhost:61616?jms.rmIdFromConnectionId=true
             </config-property>
             <connection-definitions>
                 <connection-definition class-name="org.apache.activemq.ra.ActiveMQManagedConnectionFactory" jndi-name="java:/ActiveMQConnectionFactory" enabled="true" pool-name="ConnectionFactory">
                     <xa-pool>
                         <min-pool-size>1</min-pool-size>
                         <max-pool-size>20</max-pool-size>
                         <prefill>false</prefill>
                         <is-same-rm-override>false</is-same-rm-override>
                     </xa-pool>
                 </connection-definition>
             </connection-definitions>
             <admin-objects>
                 <admin-object class-name="org.apache.activemq.command.ActiveMQQueue" jndi-name="java:/queue/OrdersQueue" use-java-context="true" pool-name="OrdersQueue">
                     <config-property name="PhysicalName">
                         OrdersQueue
                     </config-property>
                 </admin-object>
                 <admin-object class-name="org.apache.activemq.command.ActiveMQTopic" jndi-name="java:/topic/OrdersQueue" use-java-context="true" pool-name="OrdersQueue">
                     <config-property name="PhysicalName">
                         OrdersQueue
                     </config-property>
                 </admin-object>
             </admin-objects>
         </resource-adapter>

server log:

15:52:16,654 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-1) WFLYUT0018: Host default-host starting
15:52:16,901 INFO  [org.jboss.as.server.deployment.scanner] (MSC service thread 1-1) WFLYDS0013: Started FileSystemDeploymentService for
 directory C:\Users\projectwork\test\wildfly-10.1.0.Final\standalone\deployments
15:52:16,939 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0027: Starting deployment of "activemq-rar.rar" (run
time-name: "activemq-rar.rar")
15:52:17,334 INFO  [org.infinispan.factories.GlobalComponentRegistry] (MSC service thread 1-3) ISPN000128: Infinispan version: Infinispan 'Chakra' 8.2.4.Final
15:52:17,384 INFO  [org.infinispan.configuration.cache.EvictionConfigurationBuilder] (ServerService Thread Pool -- 59) ISPN000152: Passi

15:52:17,772 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-6) WFLYJCA0001: Bound data source [java:jboss/datasources/ExampleDS]
15:52:17,976 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-5) WFLYUT0006: Undertow HTTPS listener https listening on 127.0.0.1:8443
15:52:18,108 INFO  [org.jboss.ws.common.management] (MSC service thread 1-5) JBWS022052: Starting JBossWS 5.1.5.Final (Apache CXF 3.1.6)

15:52:21,318 INFO  [org.jboss.as.connector.deployers.RADeployer] (MSC service thread 1-1) IJ020001: Required license terms for file:/C:/Users/projectwork/test/wildfly-10.1.0.Final/standalone/tmp/vfs/temp/tempf22f4852ec95410f/content-66895d00372beb/contents/
15:52:21,372 WARN  [org.jboss.as.connector.deployers.RADeployer] (MSC service thread 1-1) IJ020017: Invalid archive: file:/C:/Users/projectwork/test/wildfly-10.1.0.Final/standalone/tmp/vfs/temp/tempf22f4852ec95410f/content-66895d00372beb/contents/
15:52:21,492 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 34) WFLYSRV0010: Deployed "activemq-rar.rar" (runtime-name : "activemq-rar.rar")
15:52:21,707 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:9990/management
15:52:21,707 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0051: Admin console listening on http://127.0.0.1:9990
15:52:21,708 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: WildFly Full 10.1.0.Final (WildFly Core 2.2.0.Final) started in8658ms - Started 370 of 621 services (401 services are lazy, passive or on-demand)

**Comment by sankintoo** [comment]
The standalone-full.xml
<subsystem xmlns="urn:jboss:domain:resource-adapters:4.0" >
		 <resource-adapters>
         <resource-adapter id="activemq-rar.rar">
             <archive>
                 activemq-rar.rar
             </archive>
             <transaction-support>XATransaction</transaction-support>
             <config-property name="UseInboundSession">
                 false
             </config-property>
             <config-property name="Password">
                 defaultPassword
             </config-property>
             <config-property name="UserName">
                 defaultUser
             </config-property>
             <config-property name="ServerUrl">
                 tcp://localhost:61616?jms.rmIdFromConnectionId=true
             </config-property>
             <connection-definitions>
                 <connection-definition class-name="org.apache.activemq.ra.ActiveMQManagedConnectionFactory" jndi-name="java:/ActiveMQConnectionFactory" enabled="true" pool-name="ConnectionFactory">
                     <xa-pool>
                         <min-pool-size>1</min-pool-size>
                         <max-pool-size>20</max-pool-size>
                         <prefill>false</prefill>
                         <is-same-rm-override>false</is-same-rm-override>
                     </xa-pool>
                 </connection-definition>
             </connection-definitions>
             <admin-objects>
                 <admin-object class-name="org.apache.activemq.command.ActiveMQQueue" jndi-name="java:/queue/OrdersQueue" use-java-context="true" pool-name="OrdersQueue">
                     <config-property name="PhysicalName">
                         OrdersQueue
                     </config-property>
                 </admin-object>
                 <admin-object class-name="org.apache.activemq.command.ActiveMQTopic" jndi-name="java:/topic/OrdersQueue" use-java-context="true" pool-name="OrdersQueue">
                     <config-property name="PhysicalName">
                         OrdersQueue
                     </config-property>
                 </admin-object>
             </admin-objects>
         </resource-adapter>

**Comment by jamesnetherton** [comment]
Manual deployment worked fine for me:

```
08:48:11,210 INFO  [org.jboss.as.connector.deployment] (MSC service thread 1-3) WFLYJCA0002: Bound JCA ConnectionFactory [java:/ActiveMQConnectionFactory]
08:48:11,211 INFO  [org.jboss.as.connector.deployment] (MSC service thread 1-7) WFLYJCA0002: Bound JCA AdminObject [java:/topic/HELLOWORLDMDBTopic]
08:48:11,210 INFO  [org.jboss.as.connector.deployment] (MSC service thread 1-5) WFLYJCA0002: Bound JCA AdminObject [java:/queue/HELLOWORLDMDBQueue]
```

**Comment by sankintoo** [comment]
Hello James,

as WildFly10 comes with ActiveMQ integrated, could you please comment, whether in this case the resource adapter is needed, too?

If this is the case -- what would be the functionality provided by the resource adapter on top of the present integration?

Thanks!
Sanjeev

**Comment by jamesnetherton** [comment]
It depends on your use case...

If you want to hook up to a ActiveMQ 5.x broker, then using the 5.x resource adapter makes sense.

Otherwise, you can leverage the camel-jms component together with the WildFly messaging subsystem to configure queues / topics, connect to external ActiveMQ Artemis brokers etc.

**Comment by sankintoo** [comment]
Thank you.  I used the camel-jms. It works.

**Comment by sankintoo** [comment]
Thank you.  I used the camel-jms. It works.
